# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: {{ include "final-exam-app.fullname" . }}
  labels:
    {{- include "final-exam-app.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "final-exam-app.name" . }}
  ports:
    - port: 80
      targetPort: 5001
